name: build

on:
  push:
    branches:
      - "master"
      - "flake"
      - "ga"
  pull_request:
    branches:
      - "master"

  # run workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matrix_on_mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: download ape 1
        run: sudo curl -so /usr/bin/ape https://justine.lol/ape.elf

      - name: download ape 2
        run: sudo chmod +x /usr/bin/ape

      - name: download ape 3
        run: sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

      - name: make matrix
        run: make -j2 check o//test/blink o//test/asm o//test/func o//test/metal
